### ISSUE TITLE
Add even spacing between boxes in the main page once signed in

### ISSUE THREAD

**Issue by nathan-a-macleod** [jacob-macleod/Dolphin-Flashcard-App#142]
![Screenshot_20240801_102401_Chrome.jpg](https://github.com/user-attachments/assets/cb3f1124-65c0-434b-9750-41aacb4ccd48)

In the image, the last box has more spacing above it than it should relative to the other boxes.

**Comment by jacob-macleod** [comment]
Thanks, I'll work on this

**Comment by jacob-macleod** [comment]
I've now fixed this
