### ISSUE TITLE
Adjust the text in the first box in the homepage once signed in

### ISSUE THREAD

**Issue by nathan-a-macleod** [jacob-macleod/Dolphin-Flashcard-App#143]
This image shows what it should be like:
![Screenshot_20240801_102523_Chrome.jpg](https://github.com/user-attachments/assets/c5f68a5d-5291-492e-9fe4-7f30ea912427)

So replace "days" with "day streak", and remove the "STREAK" label at the top.

**Comment by jacob-macleod** [comment]
Thanks, I'll work on this

**Comment by jacob-macleod** [comment]
This is now completed
